### ISSUE TITLE
Wikipedia.org

### ISSUE THREAD

**Issue by krystian3w** [DandelionSprout/adfilt#118]
Wikipedia tested new tiny columns (960px):

`https://fr.wikipedia.org/`
`https://eu.wikipedia.org/`

`https://fr.wiktionary.org/`

also in right to left languages:

`https://fa.wikipedia.org/`
`https://he.wikipedia.org/`

Now should help:

```css
wikipedia.org,wiktionary.org#$#[dir="ltr"] .skin-vector-max-width .mw-content-container { margin-left: 176px !important; }
wikipedia.org,wiktionary.org#$#[dir="rtl"] .skin-vector-max-width .mw-content-container { margin-right: 176px !important; }
wikipedia.org,wiktionary.org#$#.skin-vector-max-width .mw-content-container, .skin-vector-max-width .mw-workspace-container, .skin-vector-max-width .mw-page-container { max-width: unset !important; }
```
