### ISSUE TITLE
linkId

### ISSUE THREAD

**Issue by devingoodman** [DandelionSprout/adfilt#717]
## Which entry/entries are you submitting?

On line 2186

Current filter: `$removeparam=linkId,domain=amazon.*|disneyplus.com`
Update filter: `$removeparam=linkId,domain=amazon.*|cbsnews.com|disneyplus.com`

## Which things do they block, hide, or unbreak?
Removes the tracking link from [this reddit post](https://www.reddit.com/r/news/comments/zut0re/adnan_syed_hired_by_georgetown_university_after/) with a link to CBS.com news. Tracking parameter is currently not removed by list.

Edit: Parameter in question is in the CBS link, not the reddit link.

## Which of my lists are you submitting it to?
Actually Legitimate URL Shortener Tool

## Which adblocker(s) and version did you use when writing and testing the entries?

- [x] uBlock Origin
- [ ] AdGuard (Paid desktop version)
- [ ] AdGuard (Gratis browser versions that aren't Manifest V3 nor Safari)
- [ ] AdBlock (Firefox or Manifest V2)
- [ ] Adblock Plus (Firefox or Manifest V2)
- [ ] AdGuard Home
- [ ] Blokada
- [ ] I Don't Care About Cookies (The extension)
- [ ] AdNauseam

Other(s): None

Adblocker version(s): uBlock Origin: 1.46.0

## Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

```
uBlock Origin: 1.46.0

  added: 
    https://fanboy.co.nz/enhancedstats.txt: 2989-14, 13h.54m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt: 685-8, 46m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2048-75, 13h.53m
    adguard-generic: 66705-5664, 1d.22h.28m
    adguard-mobile: 8387-9, 1d.22h.31m
    adguard-spyware: 35805-3741, 1d.22h.29m
    adguard-spyware-url: 865-153, 1d.22h.32m
    block-lan: 44-0, 6d.28m
    adguard-annoyance: 61628-1701, 1d.22h.27m
    adguard-social: 19552-51, 1d.22h.30m
    fanboy-thirdparty_social: 68-0, 6d.28m
    fanboy-annoyance: 83947-5199, 6d.28m
    ublock-annoyances: 4823-8, 1d.22h.33m
  default: 
    user-filters: 15-0, never
    ublock-filters: 32376-139, 1d.22h.26m
    ublock-badware: 4241-0, 1d.22h.25m
    ublock-privacy: 302-2, 48m
    ublock-abuse: 77-0, 47m
    ublock-quick-fixes: 456-0, 13h.44m
    easylist: 61843-499, 18m
    easyprivacy: 30828-12177, 18m
    urlhaus-1: 8118-0, 13h.43m
```

## (Optional) Which browser(s) and version did you use?

Firefox: 108
