### ISSUE TITLE
mmo.ga

### ISSUE THREAD

**Issue by hawkeye116477** [DandelionSprout/adfilt#864]
### Describe the problem below this line as meticulously and detailed as possible (incl. pagelinks if any)

This is short link used by `https://www.mmoga.de`, usually in newsletters. It's safe site, but is blocked by Dandelion Sprout's Anti-Malware List with `||ga^$doc,domain=~google.ga|~filtri-dns.ga|~dgdi.ga|~9191.ga|~animevsub.ga|~my.ga|~shorturl.ga`.

### Which adblocker(s) did you use when testing this?

uBlock Origin

### Adblocker version(s)

1.49.2

### Which filterlists did you use? Failing to tell this will temporarily close the report until it has been told.

```
listset (total-discarded, last-updated): 
 added: 
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion%20Sprout's%20Anti-Malware%20List.txt: 41106-12, now
  https://raw.githubusercontent.com/FiltersHeroes/KAD/master/KAD.txt: 355034-8, now
  adguard-generic: 71133-705, now
  fanboy-social: 16072-9, now
  ublock-annoyances: 5076-50, now
 default: 
  user-filters: 29-1, never
  POL-0: 7943-20, 1m
  POL-2: 1275-13, 1m
  easylist: 66571-940, now
  easyprivacy: 31807-155, now
  plowe-0: 3724-957, now
  ublock-abuse: 69-0, now
  ublock-badware: 7151-841, now
  ublock-filters: 33248-3689, now
  ublock-privacy: 380-75, now
  ublock-quick-fixes: 314-26, now
  ublock-unbreak: 2017-91, now
  urlhaus-1: 6851-1, now

```

### Which browser(s) did you use when testing this?

Vivaldi

### Browser version(s)

6.0.2979.15 (based on Chromium 112.0.0.0)

### Which OS(s) did you use when testing this?

Linux

### OS version(s)

Manjaro 22.1.0 Talos
